services:
  dashboard:
    image: ghcr.io/lxgrf/home_dashboard:master
    container_name: dashboard_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=UTC
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=zigbee2mqtt/+/settings
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Default for Sonoff Dongle
    ports:
      - 8080:8080
    environment:
      - TZ=UTC
    depends_on:
      - mosquitto
